### ISSUE TITLE
How to work with named tables?

### ISSUE THREAD

**Issue by SvenMarquardt2718** [TheFirstAvenger/ets#18]
Currently, every function needs as first argument a struct. But when I create a named_table i want to use this functions with an atom(). Is there a reason why all functions only accept structs as the first argument and not like the erlang ets an atom()?

**Comment by TheFirstAvenger** [comment]
Thanks for bringing this issue up. The reason we require a struct is that it reduces the amount of checking we have to inject into each function to validate assumptions, and therefore simplifies the checks and reduces the chances that something could happen that we weren't expecting. We want `Ets` to be reliable and give good error messages when the developer does something incorrect, and this helps attain that goal. I have added a section to the documentation to outline the right pattern for using `Ets` in cases where you don't have the struct available to you.
