### ISSUE TITLE
RFC - lazily getting a stream of keys from an ETS table

### ISSUE THREAD

**Issue by sunaku** [TheFirstAvenger/ets#7]
Hello,

Do you think it would be useful to add `stream_keys()` and `stream_values()` functions that respectively return all keys/values from an ETS table?  I'm currently doing this to lazily handle a large ETS table as follows:

```elixir
alias Ets.Set.KeyValueSet, as: EtsMap

emap = a_very_large_instance_of_EtsMap

table = emap |> EtsMap.get_table!()

keys = # this would become stream_keys()
  Stream.iterate(:ets.first(table), &:ets.next(table, &1))
  |> Stream.take_while(fn :"$end_of_table" -> false; _else -> true end)

values = # this would become stream_values()
  keys
  |> Stream.map(&EtsMap.get!(emap, &1))
```

If you think this would be useful, I will submit a PR with tests (written per TDD, of course).

Thanks for your consideration.

**Comment by TheFirstAvenger** [comment]
@sunaku Apologies for the delay in responding to this, the email notification got overlooked. Yes, that would be an awesome addition to the KeyValueSet module. One thing to note is that it should guard against unordered sets as done [here](https://github.com/TheFirstAvenger/ets/blob/master/lib/ets/set.ex#L436) as unordered sets have inconsistent and potentially error raising behavior with first/next/prev/last.

**Comment by TheFirstAvenger** [comment]
Closing this for now. Feel free to re-open if you are able to push a PR.
